// Pure audit constants — safe to import from client components.

export const AUDIT_ACTIONS = [
  "auth.login",
  "auth.login_failed",
  "auth.logout",
  "auth.password_changed",
  "auth.password_reset_requested",
  "auth.password_reset",
  "auth.sessions_revoked",
  "organization.created",
  "organization.updated",
  "organization.status_changed",
  "user.created",
  "user.updated",
  "member.added",
  "member.role_changed",
  "member.removed",
  "settings.changed",
  "admin.action",
  "permission.denied",
  // Phase 2 — client management
  "client.created",
  "client.updated",
  "client.suspended",
  "client.activated",
  "client.deleted",
  "client.access_reset",
  "plan.changed",
  "plan.created",
  "plan.updated",
  "plan.deleted",
  "user.deleted",
  "service.enabled",
  "service.disabled",
  "whatsapp.account_added",
  "whatsapp.account_updated",
  "whatsapp.account_removed",
  // Phase 3 — connection center
  "whatsapp.connect_started",
  "whatsapp.connected",
  "whatsapp.connect_failed",
  "whatsapp.disconnected",
  "whatsapp.settings_changed",
  "whatsapp.webhook_verified",
  // Phase 4 — inbox & CRM
  "conversation.assigned",
  "conversation.status_changed",
  "contact.created",
  "contact.updated",
  "contact.deleted",
  "contact.consent_changed",
  "contacts.imported",
  "contacts.exported",
  // Phase 5 — templates, campaigns, quality
  "template.created",
  "template.updated",
  "template.submitted",
  "template.status_changed",
  "template.deleted",
  "templates.synced",
  "segment.created",
  "segment.deleted",
  "campaign.created",
  "campaign.updated",
  "campaign.reviewed",
  "campaign.scheduled",
  "campaign.started",
  "campaign.paused",
  "campaign.cancelled",
  "campaign.completed",
  "campaign.failed",
  "whatsapp.quality_changed",
  "whatsapp.account_event",
  // Phase 6 — automations
  "automation.created",
  "automation.updated",
  "automation.published",
  "automation.activated",
  "automation.deactivated",
  "automation.deleted",
  "automation.duplicated",
  "automation.test_run",
  "automation.execution_stopped",
  "automation.execution_retried",
  "automation.scheduled_run",
  "automation.webhook_secret_rotated",
  // Phase 7 — flows & AI
  "flow.created",
  "flow.updated",
  "flow.published",
  "flow.deprecated",
  "flow.deleted",
  "flow.submitted",
  "billing.invoice_created",
  "billing.invoice_paid",
  "billing.invoice_voided",
  "billing.payment_failed",
  "billing.downgrade_scheduled",
  "billing.canceled",
  "billing.resumed",
  "billing.settings_updated",
  "api_key.created",
  "api_key.updated",
  "api_key.rotated",
  "api_key.revoked",
  "webhook.created",
  "webhook.updated",
  "webhook.secret_rotated",
  "webhook.disabled",
  "webhook.deleted",
  "whatsapp.active_number_changed",
  "ai_agent.created",
  "ai_agent.updated",
  "ai_agent.status_changed",
  "ai_agent.deleted",
  "ai.handoff",
  "ai.resumed",
  "appointment.created",
  "appointment.updated",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];

/** Human-readable label for activity feeds. */
export function describeAction(action: string): string {
  const labels: Record<string, string> = {
    "auth.login": "Signed in",
    "auth.login_failed": "Failed sign-in attempt",
    "auth.logout": "Signed out",
    "auth.password_changed": "Changed password",
    "auth.password_reset_requested": "Requested a password reset",
    "auth.password_reset": "Reset password",
    "auth.sessions_revoked": "Signed out of all devices",
    "organization.created": "Organization created",
    "organization.updated": "Organization details updated",
    "organization.status_changed": "Organization status changed",
    "user.created": "User created",
    "user.updated": "User updated",
    "member.added": "Team member added",
    "member.role_changed": "Member role changed",
    "member.removed": "Team member removed",
    "settings.changed": "Settings changed",
    "admin.action": "Admin action",
    "permission.denied": "Access denied",
    "client.created": "Client created",
    "client.updated": "Client updated",
    "client.suspended": "Client suspended",
    "client.activated": "Client activated",
    "client.deleted": "Client deleted",
    "client.access_reset": "Client access reset",
    "plan.changed": "Plan changed",
    "plan.created": "Plan created",
    "plan.updated": "Plan updated",
    "plan.deleted": "Plan deleted",
    "user.deleted": "User deleted",
    "service.enabled": "Service enabled",
    "service.disabled": "Service disabled",
    "whatsapp.account_added": "WhatsApp number added",
    "whatsapp.account_updated": "WhatsApp number updated",
    "whatsapp.account_removed": "WhatsApp number removed",
    "whatsapp.connect_started": "WhatsApp connection started",
    "whatsapp.connected": "WhatsApp number connected",
    "whatsapp.connect_failed": "WhatsApp connection failed",
    "whatsapp.disconnected": "WhatsApp number disconnected",
    "whatsapp.settings_changed": "WhatsApp settings changed",
    "whatsapp.webhook_verified": "Webhook verified",
    "conversation.assigned": "Conversation assigned",
    "conversation.status_changed": "Conversation status changed",
    "contact.created": "Contact created",
    "contact.updated": "Contact updated",
    "contact.deleted": "Contact deleted",
    "contact.consent_changed": "Consent changed",
    "contacts.imported": "Contacts imported",
    "contacts.exported": "Contacts exported",
    "template.created": "Template created",
    "template.updated": "Template updated",
    "template.submitted": "Template submitted to Meta",
    "template.status_changed": "Template review status changed",
    "template.deleted": "Template deleted",
    "templates.synced": "Templates synced from Meta",
    "segment.created": "Segment saved",
    "segment.deleted": "Segment deleted",
    "campaign.created": "Campaign created",
    "campaign.updated": "Campaign updated",
    "campaign.reviewed": "Campaign compliance review run",
    "campaign.scheduled": "Campaign scheduled",
    "campaign.started": "Campaign sending started",
    "campaign.paused": "Campaign paused",
    "campaign.cancelled": "Campaign cancelled",
    "campaign.completed": "Campaign completed",
    "campaign.failed": "Campaign stopped with an error",
    "whatsapp.quality_changed": "Number quality changed",
    "whatsapp.account_event": "WhatsApp account notice from Meta",
    "automation.created": "Automation created",
    "automation.updated": "Automation draft saved",
    "automation.published": "Automation version published",
    "automation.activated": "Automation activated",
    "automation.deactivated": "Automation deactivated",
    "automation.deleted": "Automation deleted",
    "automation.duplicated": "Automation duplicated",
    "automation.test_run": "Automation test run",
    "automation.execution_stopped": "Automation run stopped",
    "automation.execution_retried": "Automation run retried",
    "automation.scheduled_run": "Scheduled automation started",
    "automation.webhook_secret_rotated": "Automation webhook secret created",
    "flow.created": "WhatsApp Flow created",
    "flow.updated": "WhatsApp Flow saved",
    "flow.published": "WhatsApp Flow published",
    "flow.deprecated": "WhatsApp Flow retired",
    "flow.deleted": "WhatsApp Flow deleted",
    "flow.submitted": "WhatsApp Flow submitted",
    "billing.invoice_created": "Invoice issued",
    "billing.invoice_paid": "Invoice paid",
    "billing.invoice_voided": "Invoice voided",
    "billing.payment_failed": "Payment failed",
    "billing.downgrade_scheduled": "Plan downgrade scheduled",
    "billing.canceled": "Subscription cancelled",
    "billing.resumed": "Scheduled plan change undone",
    "billing.settings_updated": "Billing settings updated",
    "api_key.created": "API key created",
    "api_key.updated": "API key updated",
    "api_key.rotated": "API key rotated",
    "api_key.revoked": "API key revoked",
    "webhook.created": "Webhook endpoint created",
    "webhook.updated": "Webhook endpoint updated",
    "webhook.secret_rotated": "Webhook signing secret rotated",
    "webhook.disabled": "Webhook endpoint disabled",
    "webhook.deleted": "Webhook endpoint deleted",
    "whatsapp.active_number_changed": "Active WhatsApp number changed",
    "ai_agent.created": "AI agent created",
    "ai_agent.updated": "AI agent updated",
    "ai_agent.status_changed": "AI agent status changed",
    "ai_agent.deleted": "AI agent deleted",
    "ai.handoff": "AI handed the chat to the team",
    "ai.resumed": "AI resumed in a chat",
    "appointment.created": "Appointment requested",
    "appointment.updated": "Appointment updated",
  };
  return labels[action] ?? action;
}
