import { escapeHtml } from "./template-engine";
import type { TenantProfile } from "./links";

/** Responsive, table-based HTML email in the CLINIC's branding (never MECGURA's). Body text is escaped; only the CTA is a link. */
export function renderEmailHtml(t: TenantProfile, o: { subject: string; text: string; link?: string | null; ctaLabel?: string; senderName?: string | null }): { html: string; text: string } {
  const body = o.text.replace(/\s*(?:Details|View it here|View it in your secure patient portal|Book or check details|Please book a visit|Your receipt[^:]*is in your patient portal):?\s*https?:\/\/\S+/g, "").trim();
  const paras = body.split(/\n{2,}/).map((p) => `<p style="margin:0 0 16px;font-size:16px;line-height:1.55;color:#1f2933">${escapeHtml(p).replace(/\n/g, "<br>")}</p>`).join("");
  const name = escapeHtml(o.senderName || t.name);
  const logo = t.logoUrl ? `<img src="${escapeHtml(t.logoUrl)}" alt="${name}" height="40" style="display:block;height:40px;max-width:200px;border:0">` : `<span style="font-size:20px;font-weight:700;color:#fff">${name}</span>`;
  const cta = o.link ? `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:8px 0 24px"><tr><td style="border-radius:8px;background:${t.color}"><a href="${escapeHtml(o.link)}" style="display:inline-block;padding:12px 22px;font-size:16px;font-weight:600;color:#fff;text-decoration:none">${escapeHtml(o.ctaLabel ?? "Open patient portal")}</a></td></tr></table><p style="margin:0 0 16px;font-size:13px;color:#52606d">If the button does not work, copy this link: ${escapeHtml(o.link)}<br>You will be asked to sign in. We never put medical results in an email.</p>` : "";
  const contact = [t.phone && `Phone: ${escapeHtml(t.phone)}`, t.email && escapeHtml(t.email), t.address && escapeHtml(t.address)].filter(Boolean).join(" · ");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(o.subject)}</title></head><body style="margin:0;padding:0;background:#f3f6f9"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f6f9"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background:#fff;border-radius:12px;overflow:hidden;font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif"><tr><td style="background:${t.color};padding:20px 24px">${logo}</td></tr><tr><td style="padding:28px 24px 8px"><h1 style="margin:0 0 16px;font-size:20px;color:#102a43">${escapeHtml(o.subject)}</h1>${paras}${cta}</td></tr><tr><td style="padding:16px 24px 24px;border-top:1px solid #e4e7eb;font-size:12px;line-height:1.5;color:#52606d">${name}${contact ? `<br>${contact}` : ""}<br>This is an automated message about your care. Please do not reply with medical questions; call the clinic.</td></tr></table></td></tr></table></body></html>`;
  return { html, text: `${body}${o.link ? `\n\n${o.ctaLabel ?? "Open patient portal"}: ${o.link}` : ""}\n\n— ${o.senderName || t.name}` };
}
