import type { Metadata } from "next";
import { STATUS_TONE, label, rupees, when } from "@/components/subscription/format";
import { SensitiveAction } from "@/components/platform/sensitive-action";
import { UsageMeters } from "@/components/subscription/usage-meters";
import { Alert, Card, StatusBadge } from "@/components/ui";
import { requirePagePermission } from "@/lib/auth/context";
import { listPlans } from "@/lib/services/sub-plans";
import { subscriptionDetail } from "@/lib/services/sub-admin";

export const metadata: Metadata = { title: "Clinic subscription" };
export const dynamic = "force-dynamic";
const T = ({ children }: { children: React.ReactNode }) => <th scope="col" className="p-3">{children}</th>;
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const ctx = await requirePagePermission("platform.manage"); const { id } = await params;
  const [d, plans] = await Promise.all([subscriptionDetail(ctx, id), listPlans(ctx)]);
  const s = d.subscription; const sellable = plans.filter((p) => p.status === "ACTIVE" && p.commercial); const planOpts = sellable.map((p) => ({ value: p.id, label: p.name }));
  const ivl = [{ value: "MONTHLY", label: "Monthly" }, { value: "YEARLY", label: "Yearly" }]; const base = `/api/platform/subscriptions/${id}`;
  const reason = { name: "reason", label: "Reason (kept in the audit log)", kind: "textarea" as const, required: true };
  return (
    <div className="space-y-section">
      {!d.managed && <Alert tone="info" title="No managed subscription">{d.legacyPlan ? `This clinic is on the older “${d.legacyPlan}” setup (no billing, no limits). ` : ""}Assign a plan to start billing it.</Alert>}
      {s && (
        <Card className="p-card space-y-3">
          <div className="flex flex-wrap items-center gap-3"><h2 className="type-card-title">{s.planName}</h2><StatusBadge tone={STATUS_TONE[s.status]}>{s.statusLabel}</StatusBadge><span className="type-caption">plan v{s.planVersion} · {label(s.interval)} · {rupees(s.priceMinor)} · source {label(s.source)}</span></div>
          <dl className="grid gap-2 sm:grid-cols-3"><div><dt className="type-caption">Trial</dt><dd>{s.trialStart ? `${when(s.trialStart)} – ${when(s.trialEnd)}` : "—"}</dd></div><div><dt className="type-caption">Paid period</dt><dd>{s.periodStart ? `${when(s.periodStart)} – ${when(s.periodEnd)}` : "—"}</dd></div><div><dt className="type-caption">Failed payments</dt><dd>{s.failedPaymentCount}{s.cancelAtPeriodEnd ? " · cancels at period end" : ""}</dd></div></dl>
          <div className="flex flex-wrap gap-2">
            {s.status === "TRIAL" && <SensitiveAction label="Extend trial" title="Extend trial" target={d.tenant.name} impact="Adds days to the running trial. No charge." endpoint={`${base}/extend-trial`} fields={[{ name: "days", label: "Days to add", required: true }, reason]} tone="primary" />}
            {["ACTIVE", "TRIAL", "PAST_DUE", "GRACE"].includes(s.status) && <SensitiveAction label="Suspend" title="Suspend subscription" target={d.tenant.name} impact="The clinic's access follows the 'suspended' policy. Data is kept." endpoint={`${base}/act`} body={{ act: "suspend" }} fields={[reason]} />}
            {s.status === "SUSPENDED" && <SensitiveAction label="Reactivate" title="Reactivate subscription" target={d.tenant.name} impact="Restores access without payment. If the paid period has ended, give courtesy days." endpoint={`${base}/act`} body={{ act: "reactivate" }} fields={[{ name: "extendDays", label: "Courtesy days (if the period ended)" }, reason]} tone="primary" />}
            {s.status === "ACTIVE" && <SensitiveAction label="Pause" title="Pause subscription" target={d.tenant.name} impact="Pauses the subscription; the paid period is extended by the pause on resume." endpoint={`${base}/act`} body={{ act: "pause" }} fields={[reason]} />}
            {s.status === "PAUSED" && <SensitiveAction label="Resume from pause" title="Resume subscription" target={d.tenant.name} impact="Back to active." endpoint={`${base}/act`} body={{ act: "unpause" }} fields={[reason]} tone="primary" />}
            {!["CANCELLED", "EXPIRED"].includes(s.status) && <SensitiveAction label="Cancel now" title="Cancel subscription now" target={d.tenant.name} impact="Ends the subscription immediately; unpaid invoices are voided. Data is kept." endpoint={`${base}/act`} body={{ act: "cancel" }} fields={[reason]} />}
            {!["CANCELLED", "EXPIRED"].includes(s.status) && <SensitiveAction label="Change plan (no charge)" title="Change plan" target={d.tenant.name} impact="Switches the plan immediately without an invoice. Blocked if usage exceeds the new limits." endpoint={`${base}/change-plan`} fields={[{ name: "planId", label: "Plan", kind: "select", options: planOpts, required: true }, { name: "interval", label: "Billing", kind: "select", options: ivl }, reason]} tone="primary" />}
          </div>
        </Card>
      )}
      {(!s || ["CANCELLED", "EXPIRED"].includes(s.status)) && <Card className="p-card"><h2 className="type-section-title mb-2">Assign a plan</h2><SensitiveAction label="Assign plan" title="Assign a plan" target={d.tenant.name} impact="Creates a managed subscription. Trial = no charge; Free/Active = active without an invoice; Invoice = clinic gets the first invoice." endpoint={`${base}/assign`} fields={[{ name: "planId", label: "Plan", kind: "select", options: planOpts, required: true }, { name: "interval", label: "Billing", kind: "select", options: ivl }, { name: "mode", label: "Start as", kind: "select", options: [{ value: "PAID", label: "Invoice (clinic pays)" }, { value: "TRIAL", label: "Free trial" }, { value: "ACTIVE", label: "Active, billed offline / free" }] }, reason]} tone="primary" /></Card>}
      {s && <Card className="p-card"><h2 className="type-section-title mb-3">Usage</h2><UsageMeters rows={d.usage} windowStart={null} /></Card>}
      <Card><div className="p-card pb-0"><h2 className="type-section-title">Invoices</h2></div><div className="relative overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">Invoices</caption><thead><tr className="type-caption border-b border-line bg-surface-muted"><T>Invoice</T><T>Status</T><T>Total</T><T>Balance</T><T>Actions</T></tr></thead><tbody>{d.invoices.map((i) => <tr key={i.id} className="border-b border-line last:border-0"><th scope="row" className="p-3 text-left">{i.invoiceNumber}<span className="type-caption block">{label(i.kind)} · due {when(i.dueAt)}</span></th><td className="p-3"><StatusBadge tone={STATUS_TONE[i.status]}>{label(i.status)}</StatusBadge></td><td className="p-3">{rupees(i.totalMinor)}</td><td className="p-3">{rupees(i.outstandingMinor)}</td><td className="p-3"><div className="flex flex-wrap gap-2">
        {i.outstandingMinor > 0 && ["ISSUED", "OVERDUE", "PARTIALLY_PAID"].includes(i.status) && <SensitiveAction label="Record payment" title="Record an offline payment" target={`${i.invoiceNumber} · ${d.tenant.name}`} impact="Only record money that has really arrived. Pays the invoice and activates the subscription." endpoint={`/api/platform/subscriptions/invoices/${i.id}/payment`} fields={[{ name: "amountRupees", label: "Amount received (₹)", required: true, defaultValue: String(i.outstandingMinor / 100) }, { name: "method", label: "Method", kind: "select", options: [{ value: "BANK_TRANSFER", label: "Bank transfer" }, { value: "UPI", label: "UPI" }, { value: "OTHER", label: "Cheque / other" }] }, { name: "reference", label: "Bank / UPI reference", required: true }, { name: "reason", label: "Note", required: true }]} tone="primary" />}
        {["ISSUED", "OVERDUE"].includes(i.status) && i.paidMinor === 0 && <SensitiveAction label="Void" title="Void invoice" target={i.invoiceNumber} impact="Cancels this unpaid invoice. It stays on record." endpoint={`/api/platform/subscriptions/invoices/${i.id}/void`} fields={[{ name: "reason", label: "Reason", kind: "textarea", required: true }]} />}</div></td></tr>)}</tbody></table>{!d.invoices.length && <p className="type-secondary p-6 text-center">No invoices.</p>}</div></Card>
      <Card><div className="p-card pb-0"><h2 className="type-section-title">Payments</h2></div><div className="relative overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">Payments</caption><thead><tr className="type-caption border-b border-line bg-surface-muted"><T>Receipt</T><T>Status</T><T>Amount</T><T>Refunded</T><T>Actions</T></tr></thead><tbody>{d.payments.map((p) => <tr key={p.id} className="border-b border-line last:border-0"><th scope="row" className="p-3 text-left">{p.receiptNumber ?? "—"}<span className="type-caption block">{p.provider} · {when(p.paidAt ?? p.createdAt, "Asia/Kolkata", true)}</span></th><td className="p-3"><StatusBadge tone={STATUS_TONE[p.status]}>{label(p.status)}</StatusBadge></td><td className="p-3">{rupees(p.amountMinor)}</td><td className="p-3">{rupees(p.refundedMinor)}</td><td className="p-3">{p.refundableMinor > 0 && <SensitiveAction label="Request refund" title="Request a refund" target={`${p.receiptNumber ?? p.id} · up to ${rupees(p.refundableMinor)}`} impact="Creates a refund request that must be approved, then processed. Nothing moves yet." endpoint={`/api/platform/subscriptions/payments/${p.id}/refund`} fields={[{ name: "amountRupees", label: "Refund amount (₹)", required: true, defaultValue: String(p.refundableMinor / 100) }, { name: "reason", label: "Reason", kind: "textarea", required: true }]} />}</td></tr>)}</tbody></table>{!d.payments.length && <p className="type-secondary p-6 text-center">No payments.</p>}</div></Card>
      {d.refunds.length > 0 && <Card><div className="p-card pb-0"><h2 className="type-section-title">Refunds</h2></div><div className="relative overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">Refunds</caption><thead><tr className="type-caption border-b border-line bg-surface-muted"><T>Refund</T><T>Status</T><T>Amount</T><T>Actions</T></tr></thead><tbody>{d.refunds.map((r) => <tr key={r.id} className="border-b border-line last:border-0"><th scope="row" className="p-3 text-left">{r.refundNumber}<span className="type-caption block">{r.reason}</span></th><td className="p-3"><StatusBadge tone={STATUS_TONE[r.status]}>{label(r.status)}</StatusBadge></td><td className="p-3">{rupees(r.amountMinor)}</td><td className="p-3"><div className="flex flex-wrap gap-2">
        {r.status === "REQUESTED" && <><SensitiveAction label="Approve" tone="primary" title="Approve refund" target={r.refundNumber} impact="Approves the refund. It is not paid out until processed." endpoint={`/api/platform/subscriptions/refunds/${r.id}`} body={{ decision: "APPROVED" }} /><SensitiveAction label="Reject" title="Reject refund" target={r.refundNumber} impact="Rejects the request." endpoint={`/api/platform/subscriptions/refunds/${r.id}`} body={{ decision: "REJECTED" }} /></>}
        {r.status === "APPROVED" && <SensitiveAction label="Process" tone="primary" title="Process refund" target={r.refundNumber} impact="Sends the refund through the payment provider (or records an offline refund with its reference)." endpoint={`/api/platform/subscriptions/refunds/${r.id}`} body={{ decision: "PROCESS" }} fields={[{ name: "reference", label: "Reference (offline refunds only)" }]} />}</div></td></tr>)}</tbody></table></div></Card>}
      <Card className="p-card"><h2 className="type-section-title mb-3">History</h2><ul className="space-y-1">{d.events.map((e) => <li key={e.id} className="type-secondary">{when(e.createdAt, "Asia/Kolkata", true)} — {label(e.type.replace("STATUS_", ""))}{e.note ? ` · ${e.note}` : ""} <span className="type-caption">({label(e.source)})</span></li>)}</ul>{!d.events.length && <p className="type-secondary">No history yet.</p>}</Card>
    </div>
  );
}
