/** Report export writers: CSV (formula-injection safe), XLSX (hand-written, no dependency) and a printable HTML page ("Save as PDF"). Pure. */
export type CellType = "text" | "number" | "money" | "date";
export interface Column { key: string; label: string; type?: CellType; /** shows patient identity (name/phone); removed without export_patient */ identity?: boolean }
export type Row = Record<string, string | number | null | undefined>;
export interface ReportMeta { name: string; description: string; dataSource: string; range: string; timezone: string; generatedAt: string; generatedBy: string; filters: string; note?: string; truncated?: boolean; currency?: string }

const safeText = (v: unknown) => { let s = String(v ?? ""); if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`; return s; };
const csvCell = (v: unknown, type?: CellType) => {
  if ((type === "number" || type === "money") && v !== null && v !== undefined && v !== "" && /^-?\d+(\.\d+)?$/.test(String(v))) return String(v);
  const s = safeText(v); return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
export function metaLines(m: ReportMeta): [string, string][] {
  return [["Report", m.name], ["Description", m.description], ["Data source", m.dataSource], ["Date range", m.range], ["Filters", m.filters || "None"], ["Generated at", m.generatedAt], ["Timezone", m.timezone], ["Generated by", m.generatedBy], ...(m.currency ? [["Currency", m.currency] as [string, string]] : []), ...(m.note ? [["Note", m.note] as [string, string]] : []), ...(m.truncated ? [["Truncated", "Yes — the export row limit was reached; narrow the date range"] as [string, string]] : [])];
}

/** Streams the CSV in chunks so a large report never has to be one giant string. */
export function csvChunks(meta: ReportMeta, cols: Column[], rows: Row[], chunk = 1000): string[] {
  const out: string[] = [metaLines(meta).map(([k, v]) => `${csvCell(k)},${csvCell(v)}`).join("\r\n") + "\r\n\r\n" + cols.map((c) => csvCell(c.label)).join(",") + "\r\n"];
  for (let i = 0; i < rows.length; i += chunk) out.push(rows.slice(i, i + chunk).map((r) => cols.map((c) => csvCell(r[c.key], c.type)).join(",")).join("\r\n") + "\r\n");
  return out;
}
export const toCsv = (meta: ReportMeta, cols: Column[], rows: Row[]) => csvChunks(meta, cols, rows).join("");

/* -------------------------------------------------------------- XLSX -------------------------------------------------------------- */
const CRC = (() => { const t = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; } return t; })();
export function crc32(buf: Uint8Array): number { let c = 0xffffffff; for (let i = 0; i < buf.length; i++) c = CRC[(c ^ buf[i]) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; }
const enc = new TextEncoder();
const u16 = (n: number) => [n & 0xff, (n >>> 8) & 0xff]; const u32 = (n: number) => [n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff];

/** Minimal ZIP writer using "store" (no compression): enough for a valid .xlsx. */
export function zipStore(files: { name: string; data: string }[]): Uint8Array {
  const parts: number[][] = []; const central: number[][] = []; let offset = 0;
  const d = new Date(); const dosTime = (d.getUTCHours() << 11) | (d.getUTCMinutes() << 5) | (d.getUTCSeconds() >> 1); const dosDate = (((d.getUTCFullYear() - 1980) << 9) | ((d.getUTCMonth() + 1) << 5) | d.getUTCDate());
  const bodies: Uint8Array[] = [];
  for (const f of files) {
    const name = enc.encode(f.name); const data = enc.encode(f.data); const crc = crc32(data);
    const local = [...u32(0x04034b50), ...u16(20), ...u16(0x0800), ...u16(0), ...u16(dosTime), ...u16(dosDate), ...u32(crc), ...u32(data.length), ...u32(data.length), ...u16(name.length), ...u16(0), ...name];
    parts.push(local); bodies.push(data);
    central.push([...u32(0x02014b50), ...u16(20), ...u16(20), ...u16(0x0800), ...u16(0), ...u16(dosTime), ...u16(dosDate), ...u32(crc), ...u32(data.length), ...u32(data.length), ...u16(name.length), ...u16(0), ...u16(0), ...u16(0), ...u16(0), ...u32(0), ...u32(offset), ...name]);
    offset += local.length + data.length;
  }
  const cdSize = central.reduce((a, c) => a + c.length, 0);
  const end = [...u32(0x06054b50), ...u16(0), ...u16(0), ...u16(files.length), ...u16(files.length), ...u32(cdSize), ...u32(offset), ...u16(0)];
  const total = offset + cdSize + end.length; const out = new Uint8Array(total); let p = 0;
  parts.forEach((l, i) => { out.set(l, p); p += l.length; out.set(bodies[i], p); p += bodies[i].length; });
  for (const c of central) { out.set(c, p); p += c.length; } out.set(end, p);
  return out;
}
const xml = (s: unknown) => String(s ?? "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const colName = (i: number) => { let s = ""; let n = i + 1; while (n > 0) { const r = (n - 1) % 26; s = String.fromCharCode(65 + r) + s; n = Math.floor((n - 1) / 26); } return s; };
function sheetXml(rows: (string | number | null | undefined | { n: string })[][]): string {
  const body = rows.map((r, ri) => `<row r="${ri + 1}">${r.map((v, ci) => {
    const ref = `${colName(ci)}${ri + 1}`;
    if (v === null || v === undefined || v === "") return "";
    if (typeof v === "object") return `<c r="${ref}"><v>${xml(v.n)}</v></c>`;
    if (typeof v === "number" && Number.isFinite(v)) return `<c r="${ref}"><v>${v}</v></c>`;
    return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`;
  }).join("")}</row>`).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${body}</sheetData></worksheet>`;
}
const sheetName = (s: string) => s.replace(/[\\/?*[\]:]/g, " ").slice(0, 31);
/** Real .xlsx: sheet 1 = data, sheet 2 = report information. Text cells are inline strings, so nothing is ever evaluated as a formula. */
export function toXlsx(meta: ReportMeta, cols: Column[], rows: Row[]): Uint8Array {
  const num = (v: unknown, t?: CellType) => ((t === "number" || t === "money") && v !== null && v !== undefined && v !== "" && /^-?\d+(\.\d+)?$/.test(String(v)) ? { n: String(v) } : (v as string | number | null | undefined));
  const data = [cols.map((c) => c.label), ...rows.map((r) => cols.map((c) => num(r[c.key], c.type)))];
  const info = metaLines(meta).map(([k, v]) => [k, v]);
  return zipStore([
    { name: "[Content_Types].xml", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>` },
    { name: "_rels/.rels", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>` },
    { name: "xl/workbook.xml", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xml(sheetName(meta.name) || "Report")}" sheetId="1" r:id="rId1"/><sheet name="Report information" sheetId="2" r:id="rId2"/></sheets></workbook>` },
    { name: "xl/_rels/workbook.xml.rels", data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/></Relationships>` },
    { name: "xl/worksheets/sheet1.xml", data: sheetXml(data) },
    { name: "xl/worksheets/sheet2.xml", data: sheetXml(info) },
  ]);
}

/* ------------------------------------------------------------ printable ------------------------------------------------------------ */
const h = (s: unknown) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
/** Print-friendly page (use the browser's Print → Save as PDF). No scripts, no remote resources. */
export function toPrintableHtml(meta: ReportMeta, cols: Column[], rows: Row[], clinicName: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(meta.name)} — ${h(clinicName)}</title><style>
body{font:13px/1.45 system-ui,sans-serif;color:#111;margin:24px}h1{font-size:20px;margin:0 0 4px}.meta{color:#444;margin:0 0 16px}.meta div{margin:1px 0}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:4px 6px;text-align:left;vertical-align:top}th{background:#f1f1f1}td.r{text-align:right;font-variant-numeric:tabular-nums}.hint{background:#fff7d6;border:1px solid #e5d27a;padding:8px;margin-bottom:12px}@media print{.hint{display:none}body{margin:8mm}}</style></head><body>
<p class="hint">Use your browser's <strong>Print</strong> and choose <strong>Save as PDF</strong>.</p>
<h1>${h(clinicName)} — ${h(meta.name)}</h1><div class="meta">${metaLines(meta).map(([k, v]) => `<div><strong>${h(k)}:</strong> ${h(v)}</div>`).join("")}</div>
<table><thead><tr>${cols.map((c) => `<th scope="col">${h(c.label)}</th>`).join("")}</tr></thead><tbody>${rows.map((r) => `<tr>${cols.map((c) => `<td${c.type === "money" || c.type === "number" ? ' class="r"' : ""}>${h(r[c.key])}</td>`).join("")}</tr>`).join("") || `<tr><td colspan="${cols.length}">No data for the selected period.</td></tr>`}</tbody></table></body></html>`;
}
